### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by yosssi** [yosssi/gcss#1]
- [x] Create the command-line tool
- [x] Create the syntax highlighters
  - [x] Vim
  - [x] ~~TextMate & SublimeText~~ //-> put off
- [x] ~~Create the website of GCSS~~ //-> put off
- [x] Implement the selector
- [x] Implement the declaration
- [x] Implement the at-rule
- [x] Implement the mixin
- [x] Implement the assignment
- [x] Edit `CompileBytes` & check its comment
- [x] Handling of the error return by bytes.Buffer.WriteString()
- [x] Check the Sass's functions
- [x] Comment
- [x] ~~GCSS for a Web server~~ //-> canceled
- [x] Add the race detector to the test
- [x] Add e2e tests
- [x] Return an error if a selector has a suffix of "{", "}" or a declaration has a suffix of ";"
- [x] assign a variable to a mixin parameter
- [x] selector has a single mixin
- [x] `font: 100% $font-stack`
- [x] at-rule, mixin
- [x] Fix `Compile`: See http://www.reddit.com/r/golang/comments/2gkofb/yosssigcss_pure_go_css_preprocessor/
- [x] CI which runs tests on Windows
